# Generated by Django 4.0.5 on 2023-04-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
